package stulife;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Mowy
 */
public class AboutUs extends javax.swing.JPanel {

    /**
     * Creates new form Content4
     */
    public AboutUs() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        aboutus = new javax.swing.JLabel();
        headertext2 = new javax.swing.JLabel();
        headerimg2 = new javax.swing.JLabel();
        topseparator = new javax.swing.JSeparator();
        botseparator = new javax.swing.JSeparator();
        members = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        roles = new javax.swing.JLabel();
        names = new javax.swing.JLabel();
        email = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 245, 230));
        setPreferredSize(new java.awt.Dimension(785, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(770, 770));

        jPanel2.setBackground(new java.awt.Color(255, 245, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(770, 1500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutus.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        aboutus.setForeground(new java.awt.Color(5, 75, 40));
        aboutus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutus.setText("About Us");
        jPanel2.add(aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 80));

        headertext2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        headertext2.setForeground(new java.awt.Color(5, 75, 40));
        headertext2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headertext2.setText("<html> <head>     <style>         body {             font-family: Arial, sans-serif; /* Choose a clean font */             line-height: 1.6; /* Improve readability */             margin: 20px; /* Add spacing around the content */             text-align: justify; /* Justify text for neat alignment */         }     </style> </head> <body>     <p>         Hello! We are the developers of <strong>Stulife</strong>, a group of information technology students from Quezon City University.          As students, we know how difficult it is to stay healthy amongst the heavy tasks, and we want that to change.          That's why <strong>Stulife</strong> was born. Our teamwork and dedication pushed us through, making our vision possible.          We hope that you stay healthy as you pave your way towards success!     </p> </body> </html>");
        jPanel2.add(headertext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 630, 270));

        headerimg2.setBackground(new java.awt.Color(204, 255, 204));
        headerimg2.setForeground(new java.awt.Color(0, 0, 0));
        headerimg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/groupimg.jpg"))); // NOI18N
        headerimg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerimg2.setOpaque(true);
        jPanel2.add(headerimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 350, 350));

        topseparator.setBackground(new java.awt.Color(0, 0, 0));
        topseparator.setForeground(new java.awt.Color(0, 0, 0));
        topseparator.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        topseparator.setOpaque(true);
        topseparator.setPreferredSize(new java.awt.Dimension(50, 3));
        jPanel2.add(topseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, 630, -1));

        botseparator.setBackground(new java.awt.Color(0, 0, 0));
        botseparator.setForeground(new java.awt.Color(0, 0, 0));
        botseparator.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        botseparator.setOpaque(true);
        botseparator.setPreferredSize(new java.awt.Dimension(50, 3));
        jPanel2.add(botseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1390, 630, -1));

        members.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        members.setForeground(new java.awt.Color(5, 75, 40));
        members.setText("Members");
        jPanel2.add(members, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, -1, -1));

        mail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N
        jPanel2.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1420, 50, 50));

        roles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roles.setForeground(new java.awt.Color(5, 75, 40));
        roles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roles.setText("<html>\n<head>\n    <style>\n        .role {\n            font-size: 20px;\n            font-family: 'Bebas Neue', sans-serif;\n            font-weight: bold;\n        }\n    </style>\n</head>\n<body>\n    <span class=\"role\">Project Manager:</span><br><br><br>\n    <span class=\"role\">Coders:</span><br><br><br>\n    <span class=\"role\">Designers:</span><br><br><br>\n    <span class=\"role\">Researchers:</span><br><br><br>\n    <span class=\"role\">System Analyst:</span><br><br><br>\n    <span class=\"role\">Documenter:</span><br><br><br>\n    <span class=\"role\">Coffee Maker:</span><br><br><br>\n</body>\n</html>\n\n");
        roles.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(roles, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 810, 280, 550));

        names.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        names.setForeground(new java.awt.Color(5, 75, 40));
        names.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        names.setText("<html>\n<head>\n    <style>\n        .name {\n            font-size: 20px;\n            font-family: 'Arial', sans-serif;\n        }\n    </style>\n</head>\n<body>\n    <span class=\"name\">Danielle Corene Bacani</span><br><br><br>\n    <span class=\"name\">Sandree Malay</span><br>\n    <span class=\"name\">Jhon Dave Gonzales</span><p><p>\n    <span class=\"name\">Jaira Elaine Fabia</span><br>\n    <span class=\"name\">Marilyn Mendez</span><br><br>\n    <span class=\"name\">Luigi Emanuel Britania</span><br>\n    <span class=\"name\">Yulla Mary Beatriz Ganancial</span><br><br>\n    <span class=\"name\">Russel Earl Mercado</span><br><p><p><p>\n    <span class=\"name\">Iron Salvador</span><br><p><p><p>\n    <span class=\"name\">Joshua Corcelles</span><br>\n</body>\n</html>\n");
        names.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(names, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 810, 360, 550));

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("qwerty@gmail.com");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1426, -1, 40));

        jScrollPane1.setViewportView(jPanel2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 785, 730));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutus;
    private javax.swing.JSeparator botseparator;
    private javax.swing.JLabel email;
    private javax.swing.JLabel headerimg2;
    private javax.swing.JLabel headertext2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel members;
    private javax.swing.JLabel names;
    private javax.swing.JLabel roles;
    private javax.swing.JSeparator topseparator;
    // End of variables declaration//GEN-END:variables
}
