package stulife;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Mowy
 */
public class EditProfile extends javax.swing.JPanel {

    /**
     * Creates new form content
     */
    public EditProfile(JFrame frame, JPanel panel) {
        this.parentFrame = frame;
        this.parentPanel = panel; 
        initComponents();
        
        String userName,userPass,userGender,userNumber;
        int userHeight, userWeight, userBudget;
        
        buttonGroup.add(male);
        buttonGroup.add(female);
        
        
        User user = new User();
        
        connection.start();
        
        
        userName = user.getUsername();
        userPass = user.getPassword();
        userHeight = user.getHeight();
        userWeight = user.getWeight();
        userBudget = user.getBudget();
        userGender = user.getGender();
        userNumber = user.getNumber();
        
        if (userGender.equals("m")) {
            male.setSelected(true);
        } else {
            female.setSelected(true);
        }
        
        bmi = new BMICalculator(userHeight, userWeight);
        bmi.calculate();
        
        bmitext.setText("BMI: " + BMICalculator.getBMI());
        
        name.setText(User.getUsername());
        password.setText(User.getPassword());
        height.setText(String.valueOf(User.getHeight()));
        weight.setText(String.valueOf(User.getWeight()));
        budget.setText(String.valueOf(User.getBudget()));
        number.setText(userNumber);
        
        String formattedDate = User.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("MMMM dd, yyyy");
        try {
            Date fdate = formatter.parse(formattedDate);
            // Set the date in the JDateChooser
            date.setDate(fdate);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }
    
    public void update() {
        
        String SUrl, SUser, SPass;
        SUrl = "jdbc:mysql://localhost:3306/stulife_user";
        SUser = "root";
        SPass = "";
        
        
        try {
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            int quantity, calories, multiply, totalCalories = 0;
            
            int id = user.getId();
            
            String query = "SELECT * FROM food WHERE userID = ?";
            
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setInt(1, id);
            
            ResultSet rs = pst.executeQuery();
            
            // Process the result set
            while (rs.next()) {
                quantity = rs.getInt("quantity");
                calories = rs.getInt("calories");
                multiply = quantity * calories;
                totalCalories += multiply;
                
            }
            caloriesnum.setText(String.valueOf(totalCalories) + " / 2500");
            
            double progressFraction = (double) totalCalories / 2500; // Cast to double
            int progressbarnum = (int) (progressFraction * 100); // Scale to 0-100 range
            
            progressbar.setValue(progressbarnum);
            
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        budgettext = new javax.swing.JLabel();
        budget = new javax.swing.JTextArea();
        bmiimg = new javax.swing.JLabel();
        phsign = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        birthday = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        budgetborder = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        logout = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        passshow = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        caloriesintake = new javax.swing.JLabel();
        caloriesbar = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();
        goaltext = new javax.swing.JLabel();
        caloriesnum = new javax.swing.JLabel();
        bmitext = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 245, 230));
        setMinimumSize(new java.awt.Dimension(100, 600));
        setPreferredSize(new java.awt.Dimension(770, 770));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        budgettext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        budgettext.setForeground(new java.awt.Color(5, 75, 40));
        budgettext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        budgettext.setText("Budget");
        add(budgettext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 80, 30));

        budget.setBackground(new java.awt.Color(153, 199, 162));
        budget.setColumns(20);
        budget.setForeground(new java.awt.Color(0, 0, 0));
        budget.setRows(5);
        budget.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 1));
        add(budget, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 80, 20));

        bmiimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bmiimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmi.png"))); // NOI18N
        add(bmiimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 150, 150));

        phsign.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        phsign.setForeground(new java.awt.Color(0, 0, 0));
        phsign.setText("₱");
        add(phsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 30, 20));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.setText("Name:");
        name.setMargin(new java.awt.Insets(2, 12, 2, 6));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                namePropertyChange(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 330, 50));

        height.setBackground(new java.awt.Color(255, 255, 255));
        height.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        height.setText("Height:");
        height.setMargin(new java.awt.Insets(2, 12, 2, 6));
        height.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                heightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                heightFocusLost(evt);
            }
        });
        add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 160, 50));

        weight.setBackground(new java.awt.Color(255, 255, 255));
        weight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        weight.setText("Weight:");
        weight.setMargin(new java.awt.Insets(2, 12, 2, 6));
        weight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                weightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                weightFocusLost(evt);
            }
        });
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 160, 50));

        age.setBackground(new java.awt.Color(255, 255, 255));
        age.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        age.setText("Age:");
        age.setMargin(new java.awt.Insets(2, 12, 2, 6));
        age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFocusLost(evt);
            }
        });
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 90, 50));

        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateKeyTyped(evt);
            }
        });
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 150, -1));

        birthday.setEditable(false);
        birthday.setBackground(new java.awt.Color(255, 255, 255));
        birthday.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        birthday.setText("Birthday:");
        birthday.setMargin(new java.awt.Insets(2, 12, 2, 6));
        birthday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthdayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                birthdayFocusLost(evt);
            }
        });
        add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 230, 50));

        male.setText("Male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        male.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        male.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleMouseClicked(evt);
            }
        });
        add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 110, 30));

        female.setText("Female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        female.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        female.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleMouseClicked(evt);
            }
        });
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 100, 30));

        budgetborder.setBackground(new java.awt.Color(255, 255, 255));
        budgetborder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        budgetborder.setOpaque(true);
        add(budgetborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 140, 60));

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gender.setOpaque(true);
        add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 330, 30));

        go.setBackground(new java.awt.Color(255, 255, 255));
        go.setForeground(new java.awt.Color(0, 0, 0));
        go.setText("Go");
        go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go.setOpaque(true);
        go.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goMouseClicked(evt);
            }
        });
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 100, 30));

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setForeground(new java.awt.Color(0, 0, 0));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Log out");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 70, 20));

        number.setBackground(new java.awt.Color(255, 255, 255));
        number.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        number.setText("Phone Number:");
        number.setMargin(new java.awt.Insets(2, 12, 2, 6));
        number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberFocusLost(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 330, 50));

        passshow.setBackground(new java.awt.Color(204, 204, 204));
        passshow.setAlignmentY(0.0F);
        passshow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passshow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passshow.setOpaque(true);
        passshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passshowMouseClicked(evt);
            }
        });
        add(passshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 245, 20, 20));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        password.setMargin(new java.awt.Insets(2, 12, 2, 6));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 330, 50));

        caloriesintake.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        caloriesintake.setForeground(new java.awt.Color(5, 75, 40));
        caloriesintake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caloriesintake.setText("Calories Intake");
        add(caloriesintake, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 150, -1));

        caloriesbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calorieintake.png"))); // NOI18N
        caloriesbar.setText("jLabel2");
        add(caloriesbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 150, 30));

        progressbar.setBackground(new java.awt.Color(255, 255, 255));
        progressbar.setForeground(new java.awt.Color(255, 255, 255));
        progressbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 130, 20));

        goaltext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        goaltext.setForeground(new java.awt.Color(5, 75, 40));
        goaltext.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goaltext.setText("Calories:");
        goaltext.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(goaltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 130, 30));

        caloriesnum.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        caloriesnum.setForeground(new java.awt.Color(0, 0, 0));
        caloriesnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caloriesnum.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        caloriesnum.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                caloriesnumPropertyChange(evt);
            }
        });
        add(caloriesnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 130, 30));

        bmitext.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        bmitext.setForeground(new java.awt.Color(5, 75, 40));
        bmitext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bmitext.setText("BMI: " + BMICalculator.getBMI());
        bmitext.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bmitextPropertyChange(evt);
            }
        });
        add(bmitext, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if (name.getText().equals("Name:")) {
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if (name.getText().equals("")) {
            name.setText("Name:");
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void heightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightFocusGained
        // TODO add your handling code here:
        if (height.getText().equals("Height:")) {
            height.setText("");
        }
    }//GEN-LAST:event_heightFocusGained

    private void heightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightFocusLost
        // TODO add your handling code here:
        if (height.getText().equals("")) {
            height.setText("Height:");
        }
    }//GEN-LAST:event_heightFocusLost

    private void weightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightFocusGained
        // TODO add your handling code here:
        if (weight.getText().equals("Weight:")) {
            weight.setText("");
        }
    }//GEN-LAST:event_weightFocusGained

    private void weightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightFocusLost
        // TODO add your handling code here:
        if (weight.getText().equals("")) {
            weight.setText("Weight:");
        }
    }//GEN-LAST:event_weightFocusLost

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusGained
        // TODO add your handling code here:
        if (age.getText().equals("Age:")) {
            age.setText("");
        }
    }//GEN-LAST:event_ageFocusGained

    private void ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusLost
        // TODO add your handling code here:
        if (age.getText().equals("")) {
            age.setText("Age:");
        }
    }//GEN-LAST:event_ageFocusLost

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void birthdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthdayFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayFocusGained

    private void birthdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthdayFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayFocusLost

    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange

        // TODO add your handling code here:

        if (date.getDate() != null) {
            Date dateChoosed = date.getDate(); // Get the selected date
            Calendar selectedDate = Calendar.getInstance();
            selectedDate.setTime(dateChoosed); // Set the selected date into a Calendar object

            // Get the current date
            Calendar currentDate = Calendar.getInstance();

            // Calculate the age
            int ageCalc = currentDate.get(Calendar.YEAR) - selectedDate.get(Calendar.YEAR);

            // Adjust the age if the current date is before the birthday in the current year
            if (currentDate.get(Calendar.MONTH) < selectedDate.get(Calendar.MONTH) ||
                (currentDate.get(Calendar.MONTH) == selectedDate.get(Calendar.MONTH) &&
                 currentDate.get(Calendar.DAY_OF_MONTH) < selectedDate.get(Calendar.DAY_OF_MONTH))) {
                ageCalc--;
            }
            age.setText(String.valueOf(ageCalc)); // Set the calculated age in the JTextField
        }

    }//GEN-LAST:event_datePropertyChange

    private void dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateKeyPressed

    private void dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_dateKeyTyped

    private void maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleMouseClicked

    }//GEN-LAST:event_maleMouseClicked

    private void femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleMouseClicked

    }//GEN-LAST:event_femaleMouseClicked

    private void namePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_namePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_namePropertyChange

    private void goMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goMouseClicked
        // TODO add your handling code here:
        String gender;
        if (male.isSelected()) {
            gender = "m";
        } else if (female.isSelected()) {
        gender = "f";
        } else {
            JOptionPane.showMessageDialog(this, "Please select a gender.");
            return;
        }
        
        if (name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name cannot be empty.");
            return;
        }
        if (password.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty.");
            return;
        }
        if (height.getText().isEmpty() || !isNumeric(height.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid height.");
            return;
        }
        if (weight.getText().isEmpty() || !isNumeric(weight.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid weight.");
            return;
        }
        if (age.getText().isEmpty() || !isNumeric(age.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid age.");
            return;
        }
        if (budget.getText().isEmpty() || !isNumeric(budget.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid budget.");
            return;
        }
        if (date.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a date.");
            return;
        }
        if (number.getText().length() != 11) {
            JOptionPane.showMessageDialog(this, "Phone Number must be 11 digits");
            return;
        }
        
            connection.change(name.getText(), String.valueOf(password.getPassword()), Integer.valueOf(height.getText()), Integer.valueOf(weight.getText()), String.valueOf(date.getDate()), gender, Integer.valueOf(age.getText()), Integer.valueOf(budget.getText()), number.getText());

            parentFrame.dispose();
            HomeFrame hf = new HomeFrame();
            hf.setVisible(true);
        
    }//GEN-LAST:event_goMouseClicked
    
    private boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        parentFrame.dispose();
        Login f = new Login();
        f.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusGained
        if (number.getText().equals("Phone Number:")) {
            number.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_numberFocusGained

    private void numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusLost
        if (number.getText().isEmpty()) {
            number.setText("Phone Number:");
        }
    }//GEN-LAST:event_numberFocusLost

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void passshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passshowMouseClicked

        if (hide) {
            password.setEchoChar('*');
            passshow.setBackground(new Color(204,204,204));
        } else {
            password.setEchoChar((char)0);
            passshow.setBackground(Color.white);
        }
        hide = !hide;
    }//GEN-LAST:event_passshowMouseClicked

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if (String.valueOf(password.getPassword()).equals("Password:")) {
            password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (String.valueOf(password.getPassword()).isEmpty()) {
            password.setText("Password:");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void caloriesnumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_caloriesnumPropertyChange

    }//GEN-LAST:event_caloriesnumPropertyChange

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        update();
    }//GEN-LAST:event_formPropertyChange

    private void bmitextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bmitextPropertyChange

    }//GEN-LAST:event_bmitextPropertyChange

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthday;
    private javax.swing.JLabel bmiimg;
    private javax.swing.JLabel bmitext;
    private javax.swing.JTextArea budget;
    private javax.swing.JLabel budgetborder;
    private javax.swing.JLabel budgettext;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel caloriesbar;
    private javax.swing.JLabel caloriesintake;
    private javax.swing.JLabel caloriesnum;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender;
    private javax.swing.JButton go;
    private javax.swing.JLabel goaltext;
    private javax.swing.JTextField height;
    private javax.swing.JLabel logout;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JLabel passshow;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel phsign;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
    private User user;
    private BMICalculator bmi;
    private int ageCalc;
    private SQLConnection connection = new SQLConnection();
    private JFrame parentFrame;
    private JPanel parentPanel;
    private boolean hide = false;
}
