package stulife;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mowy
 */
public class HomeFrame extends javax.swing.JFrame {
    public HomeFrame() {
        initComponents();
        setTitle("Home");
        setLocationRelativeTo(null);
        setResizable(false);
        
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/stulife_user";
        SUser = "root";
        SPass = "";
        
        User user = new User();
        
        
        try (Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement()) {
            
            
            
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
        
        //homeButton.setContentAreaFilled(false);     // Makes the button transparent
        homeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //editProfile.setContentAreaFilled(false);     // Makes the button transparent
        editProfile.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //settings.setContentAreaFilled(false);     // Makes the button transparent
        settings.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //aboutUs.setContentAreaFilled(false);     // Makes the button transparent
        aboutUs.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        panel.setBackground(new Color(255, 255, 255));
        panel.setOpaque(true);
        
        jp.jPanelLoader(panel, con1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        settings = new javax.swing.JButton();
        editProfile = new javax.swing.JButton();
        aboutUs = new javax.swing.JButton();
        refresh = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 0));
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 70));

        settings.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        settings.setForeground(new java.awt.Color(0, 0, 0));
        settings.setText("Meal Plan");
        settings.setBorder(null);
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        getContentPane().add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 70));

        editProfile.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        editProfile.setForeground(new java.awt.Color(0, 0, 0));
        editProfile.setText("Edit Profile");
        editProfile.setBorder(null);
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
        });
        editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileActionPerformed(evt);
            }
        });
        getContentPane().add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 230, 70));

        aboutUs.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        aboutUs.setForeground(new java.awt.Color(0, 0, 0));
        aboutUs.setText("About us");
        aboutUs.setBorder(null);
        aboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsMouseClicked(evt);
            }
        });
        getContentPane().add(aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 230, 70));

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        refresh.setForeground(new java.awt.Color(0, 0, 0));
        refresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refresh.setText("refresh");
        refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refresh.setOpaque(true);
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 50, 20));

        Home.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaper.png"))); // NOI18N
        Home.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -12, 230, 790));

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 790, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        // TODO add your handling code here:
        setTitle("Edit Profile");
        jp.jPanelLoader(panel, con2);
    }//GEN-LAST:event_editProfileMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        setTitle("Home");
        jp.jPanelLoader(panel, con1);
    }//GEN-LAST:event_homeButtonMouseClicked

    private void aboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsMouseClicked
        // TODO add your handling code here:
        setTitle("About Us");
        jp.jPanelLoader(panel, con4);
    }//GEN-LAST:event_aboutUsMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        // TODO add your handling code here:
        setTitle("Meal Plan");
        
        if (BMI.BMI() < 18.5){
            jp.jPanelLoader(panel, mpuw);
        }else if (BMI.BMI() >=  18.5 && BMI.BMI() <= 24.9) {
            jp.jPanelLoader(panel, mpn);
        }else if (BMI.BMI() >= 25 && BMI.BMI() <= 29.9) {
            jp.jPanelLoader(panel, mpow);
        } else {
            jp.jPanelLoader(panel, mpo);
        }
    }//GEN-LAST:event_settingsMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshMouseClicked

    private void editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
                
                
                
                Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                System.out.println("Application is shutting down. Stopping XAMPP...");
                XAMPPCommand.stop();

                }));
            }
        });
    }
    
    public void refresh() {
        this.dispose();
        
        HomeFrame hom = new HomeFrame();
        hom.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JButton aboutUs;
    private javax.swing.JButton editProfile;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel refresh;
    private javax.swing.JButton settings;
    // End of variables declaration//GEN-END:variables
    public JpanelLoader jp = new JpanelLoader();
    private Home con1 = new Home(this);
    private EditProfile con2 = new EditProfile(this, panel);
    private AboutUs con4 = new AboutUs();
    private MealPlanUnderweight mpuw = new MealPlanUnderweight();
    private MealPlanNormal mpn = new MealPlanNormal();
    private MealPlanOverweight mpow = new MealPlanOverweight();
    private MealPlanObesity mpo = new MealPlanObesity();
    private BMICalculator BMI;
}
