package stulife;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Timer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mowy
 */
public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
        setTitle("Login");
        setLocationRelativeTo(null);
        setResizable(false);
        
        login.setCursor(new Cursor(Cursor.HAND_CURSOR));
        signup.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        SQLConnection sqlcon = new SQLConnection();
        sqlcon.createDB();
        
        background.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passshow = new javax.swing.JLabel();
        forgotpassword = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        signup = new javax.swing.JLabel();
        donthaveanacc = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 160, 140));

        passshow.setBackground(new java.awt.Color(204, 204, 204));
        passshow.setAlignmentY(0.0F);
        passshow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passshow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passshow.setOpaque(true);
        passshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passshowMouseClicked(evt);
            }
        });
        getContentPane().add(passshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 335, 20, 20));

        forgotpassword.setForeground(new java.awt.Color(0, 255, 255));
        forgotpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotpassword.setText("<HTML><U>Forgot Password</U></HTML>");
        forgotpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseClicked(evt);
            }
        });
        getContentPane().add(forgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 100, -1));

        header1.setBackground(new java.awt.Color(255, 255, 255));
        header1.setFont(new java.awt.Font("Cooper Black", 0, 72)); // NOI18N
        header1.setForeground(new java.awt.Color(36, 96, 76));
        header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header1.setText("STULIFE");
        header1.setToolTipText("");
        header1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 124));

        header2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        header2.setForeground(new java.awt.Color(36, 96, 76));
        header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header2.setText("STUDENT LIFESTYLE");
        getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1020, -1));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setText("Name");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 330, 50));

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 100, 30));

        signup.setForeground(new java.awt.Color(0, 255, 255));
        signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup.setText("<HTML><U>Sign up</U></HTML>");
        signup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                signupMouseDragged(evt);
            }
        });
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 80, -1));

        donthaveanacc.setForeground(new java.awt.Color(255, 255, 255));
        donthaveanacc.setText("Don't have an account?");
        donthaveanacc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                donthaveanaccMouseDragged(evt);
            }
        });
        donthaveanacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donthaveanaccMouseEntered(evt);
            }
        });
        getContentPane().add(donthaveanacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 150, -1));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("Password");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 330, 50));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaper.png"))); // NOI18N
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if (name.getText().equals("Name")) {
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if (name.getText().equals("")) {
            name.setText("Name");
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void donthaveanaccMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donthaveanaccMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_donthaveanaccMouseDragged

    private void donthaveanaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donthaveanaccMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_donthaveanaccMouseEntered

    private void signupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_signupMouseDragged

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
       
       this.dispose();
       SignUp su = new SignUp();
       su.setVisible(true);
       
    }//GEN-LAST:event_signupMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        String SUrl, SUser, SPass, passDb = null;
        SUrl = "jdbc:MySQL://localhost:3306/stulife_user";
        SUser = "root";
        SPass = "";
        boolean found = false;
        
        try {
            String userName, userPass, query;
            
            
            
            
            if (name.getText().equals("Name")) {
                JOptionPane.showMessageDialog(new JFrame(),"Name is blank", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (password.getPassword().equals("")) {
                JOptionPane.showMessageDialog(new JFrame(),"Password is blank", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                
                userName = name.getText();
                userPass = String.valueOf(password.getPassword());
                
                User user = new User();
                user.setUsername(userName);
                user.setPassword(userPass);
                
                query = "SELECT password FROM user_info WHERE username = ?";
                Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, userName);
                
                ResultSet rs = pst.executeQuery();
                
                
                while(rs.next()) {
                    passDb = rs.getString("password");
                    found = true;
                }
                
                if (found && userPass.equals(passDb)) {
                    this.dispose();
                    HomeFrame home = new HomeFrame();
                    home.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(new JFrame(),"Incorrect name or password", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                
                name.setText("");
                password.setText("");
            }
            
            
            
        } catch (Exception e) {
            System.out.println("Error!" + e.getMessage());
        }
    }//GEN-LAST:event_loginMouseClicked

    private void forgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseClicked
        ForgotPassword fp = new ForgotPassword();
        this.dispose();
        fp.setVisible(true);
        
    }//GEN-LAST:event_forgotpasswordMouseClicked

    private void passshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passshowMouseClicked
        
        
        if (hide) {
            password.setEchoChar('*');
            passshow.setBackground(new Color(204,204,204));
        } else {
            password.setEchoChar((char)0);
            passshow.setBackground(Color.white);
        }
        hide = !hide;
    }//GEN-LAST:event_passshowMouseClicked

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (String.valueOf(password.getPassword()).isEmpty()) {
            password.setText("Password");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if (String.valueOf(password.getPassword()).equals("Password")) {
            password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
        XAMPPCommand.start();
        
        new Login().setVisible(true);
        
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
        System.out.println("Application is shutting down. Stopping XAMPP...");
        XAMPPCommand.stop();
        
        }));
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel donthaveanacc;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JLabel passshow;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel signup;
    // End of variables declaration//GEN-END:variables
    private boolean hide = false;
}
