package stulife;


import java.awt.*;
import java.beans.PropertyChangeListener;
import javax.swing.JFrame;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.Year;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mowy
 */
public class SignUp extends JFrame {

    /**
     * Creates new form Frame
     */
    public SignUp() {
        initComponents();
        setTitle("Signup");
        setLocationRelativeTo(null);
        setResizable(false);
        
        login.setCursor(new Cursor(Cursor.HAND_CURSOR));
        signup.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        gender.setOpaque(true);
        gender.setBackground(Color.WHITE);
        
        
        buttonGroup.add(male);
        buttonGroup.add(female);
        
        password.setEchoChar((char)0);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        header1 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        passshow = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        number = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        cm = new javax.swing.JLabel();
        kg = new javax.swing.JLabel();
        alreadyhaveanacc = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        birthday = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        gender = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setBackground(new java.awt.Color(255, 255, 255));
        header1.setFont(new java.awt.Font("Cooper Black", 0, 72)); // NOI18N
        header1.setForeground(new java.awt.Color(36, 96, 76));
        header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header1.setText("STULIFE");
        header1.setToolTipText("");
        header1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 124));

        header2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        header2.setForeground(new java.awt.Color(36, 96, 76));
        header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header2.setText("STUDENT LIFESTYLE");
        getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1020, -1));

        passshow.setBackground(new java.awt.Color(204, 204, 204));
        passshow.setAlignmentY(0.0F);
        passshow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passshow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passshow.setOpaque(true);
        passshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passshowMouseClicked(evt);
            }
        });
        getContentPane().add(passshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 275, 20, 20));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        password.setMargin(new java.awt.Insets(2, 12, 2, 6));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 330, 50));

        number.setBackground(new java.awt.Color(255, 255, 255));
        number.setForeground(new java.awt.Color(102, 102, 102));
        number.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        number.setText("Phone Number:");
        number.setMargin(new java.awt.Insets(2, 12, 2, 6));
        number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberFocusLost(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 330, 50));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.setText("Name:");
        name.setMargin(new java.awt.Insets(2, 12, 2, 6));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 330, 50));

        cm.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cm.setText("cm");
        getContentPane().add(cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        kg.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        kg.setText("kg");
        getContentPane().add(kg, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        alreadyhaveanacc.setForeground(new java.awt.Color(255, 255, 255));
        alreadyhaveanacc.setText("Already have an account?");
        alreadyhaveanacc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                alreadyhaveanaccMouseDragged(evt);
            }
        });
        alreadyhaveanacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alreadyhaveanaccMouseEntered(evt);
            }
        });
        getContentPane().add(alreadyhaveanacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 150, -1));

        login.setForeground(new java.awt.Color(0, 255, 255));
        login.setText("<HTML><U>Log in</U></HTML>");
        login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginMouseDragged(evt);
            }
        });
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 60, -1));

        height.setBackground(new java.awt.Color(255, 255, 255));
        height.setForeground(new java.awt.Color(102, 102, 102));
        height.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        height.setText("Height:");
        height.setMargin(new java.awt.Insets(2, 12, 2, 6));
        height.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                heightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                heightFocusLost(evt);
            }
        });
        getContentPane().add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 160, 50));

        age.setBackground(new java.awt.Color(255, 255, 255));
        age.setForeground(new java.awt.Color(102, 102, 102));
        age.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        age.setText("Age:");
        age.setMargin(new java.awt.Insets(2, 12, 2, 6));
        age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFocusLost(evt);
            }
        });
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 90, 50));

        weight.setBackground(new java.awt.Color(255, 255, 255));
        weight.setForeground(new java.awt.Color(102, 102, 102));
        weight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        weight.setText("Weight:");
        weight.setMargin(new java.awt.Insets(2, 12, 2, 6));
        weight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                weightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                weightFocusLost(evt);
            }
        });
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        getContentPane().add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 160, 50));

        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateKeyTyped(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 150, -1));

        birthday.setEditable(false);
        birthday.setBackground(new java.awt.Color(255, 255, 255));
        birthday.setForeground(new java.awt.Color(102, 102, 102));
        birthday.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        birthday.setText("Birthday:");
        birthday.setMargin(new java.awt.Insets(2, 12, 2, 6));
        birthday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthdayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                birthdayFocusLost(evt);
            }
        });
        getContentPane().add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 230, 50));

        male.setForeground(new java.awt.Color(102, 102, 102));
        male.setText("Male");
        male.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        male.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleMouseClicked(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 110, 30));

        female.setForeground(new java.awt.Color(102, 102, 102));
        female.setText("Female");
        female.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        female.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleMouseClicked(evt);
            }
        });
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 100, 30));

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gender.setOpaque(true);
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 330, 30));

        signup.setBackground(new java.awt.Color(255, 255, 255));
        signup.setText("Sign Up");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 80, 30));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaper.png"))); // NOI18N
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if (name.getText().equals("Name:")) {
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if (name.getText().equals("")) {
            name.setText("Name:");
        }
    }//GEN-LAST:event_nameFocusLost

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void alreadyhaveanaccMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyhaveanaccMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_alreadyhaveanaccMouseDragged

    private void alreadyhaveanaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyhaveanaccMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alreadyhaveanaccMouseEntered

    private void loginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseDragged

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
       this.dispose();
       Login lin = new Login();
       lin.setVisible(true);
    }//GEN-LAST:event_loginMouseClicked

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void birthdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthdayFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayFocusGained

    private void birthdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthdayFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayFocusLost

    private void heightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightFocusGained
        // TODO add your handling code here:
        if (height.getText().equals("Height:")) {
            height.setText("");
        }
    }//GEN-LAST:event_heightFocusGained

    private void heightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightFocusLost
        // TODO add your handling code here:
        if (height.getText().equals("")) {
            height.setText("Height:");
        }
    }//GEN-LAST:event_heightFocusLost

    private void ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusGained
        // TODO add your handling code here:
        if (age.getText().equals("Age:")) {
            age.setText("");
        }
    }//GEN-LAST:event_ageFocusGained

    private void ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusLost
        // TODO add your handling code here:
        if (age.getText().equals("")) {
            age.setText("Age:");
        }
    }//GEN-LAST:event_ageFocusLost

    private void maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleMouseClicked
        // TODO add your handling code here:
        /*if (male.isSelected()) {
            female.setEnabled(false);  // Disable the female radio button when male is selected
        } else {
            female.setEnabled(true);   // Re-enable female radio button if male is not selected
        }
        */
    }//GEN-LAST:event_maleMouseClicked

    private void femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleMouseClicked
        // TODO add your handling code here:
        /*
        if (female.isSelected()) {
            male.setEnabled(false);    // Disable the male radio button when female is selected
        } else {
            male.setEnabled(true);     // Re-enable male radio button if female is not selected
        }
        */
    }//GEN-LAST:event_femaleMouseClicked

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/stulife_user";
        SUser = "root";
        SPass = "";
        
        if ("".equals(name.getText())) {
                JOptionPane.showMessageDialog(new JFrame(),"Full name is require", "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error");
            }
        
        try {
            
            String userName, userPass, query, userNumber;
            int userHeight, userWeight, userAge;
            Date userBirthday;
            char userGender;
            
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            
            if (name.getText().equals("Name:")) {
                JOptionPane.showMessageDialog(new JFrame(),"Name is blank", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (password.getPassword().equals("Password:")) {
                JOptionPane.showMessageDialog(new JFrame(),"Password is blank", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (height.getText().equals("Height:") || Integer.parseInt(height.getText()) < 0) {
                JOptionPane.showMessageDialog(new JFrame(),"Error in Height Field", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (weight.getText().equals("Weight:") || Integer.parseInt(weight.getText()) < 0) {
                JOptionPane.showMessageDialog(new JFrame(),"Error in Weight Field", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (date.getDate() == null) {
                JOptionPane.showMessageDialog(new JFrame(),"Birthday is blank", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (age.getText() == null || Integer.parseInt(age.getText()) < 0) {
                JOptionPane.showMessageDialog(new JFrame(),"Age should be greater than 0", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (buttonGroup.getSelection() == null) {
                JOptionPane.showMessageDialog(new JFrame(),"Please select a gender", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (number.getText().equals("Phone Number:") || number.getText().length() != 11) {
                JOptionPane.showMessageDialog(new JFrame(),"Phone Number should have 11 digits", "Error", JOptionPane.ERROR_MESSAGE);
            } else {    
                
                userName = name.getText();
                String checkUserQuery = "SELECT COUNT(*) AS count FROM user_info WHERE username = ?";
                PreparedStatement pstCheck = con.prepareStatement(checkUserQuery);
                pstCheck.setString(1, userName);
                ResultSet rsCheck = pstCheck.executeQuery();
                rsCheck.next();

                int count = rsCheck.getInt("count");
                
                if (count > 0) {
                    // If username already exists, show an error message
                    JOptionPane.showMessageDialog(new JFrame(),"Username is already taken. Please choose another username.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                
                    if (male.isSelected()) {
                        userGender = 'm';
                    } else {
                        userGender = 'f';
                    }

                    userName = name.getText();
                    userPass = String.valueOf(password.getPassword());
                    userHeight = Integer.parseInt(height.getText());
                    userWeight = Integer.parseInt(weight.getText());
                    userAge = Integer.parseInt(age.getText());
                    userNumber = number.getText();
                    
                    userBirthday = date.getDate();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String formattedDate = dateFormat.format(userBirthday);

                    query = "INSERT INTO user_info (username, password, height, weight, birthday, gender, age, phone_number) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement pstInsert = con.prepareStatement(query);
                    pstInsert.setString(1, userName);
                    pstInsert.setString(2, userPass);
                    pstInsert.setInt(3, userHeight);
                    pstInsert.setInt(4, userWeight);
                    pstInsert.setString(5, formattedDate);
                    pstInsert.setString(6, String.valueOf(userGender));
                    pstInsert.setInt(7, userAge);
                    pstInsert.setString(8, userNumber);
                    pstInsert.executeUpdate();

                    // Clear fields after successful registration
                    name.setText("");
                    password.setText("");
                    height.setText("");
                    weight.setText("");
                    age.setText("");
                    date.cleanup();
                    buttonGroup.clearSelection();
                    number.setText("");
                    
                    showMessageDialog(null, "Account has been created successfully");
                    this.dispose();
                    Login lin = new Login();
                    lin.setVisible(true);
                    
                    
                }
            }
            
            
            
        } catch (Exception e) {
            System.out.println("Error! " + e.getMessage());
        }
        
    }//GEN-LAST:event_signupMouseClicked

    private void weightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightFocusGained
        // TODO add your handling code here:
        if (weight.getText().equals("Weight:")) {
            weight.setText("");
        }
    }//GEN-LAST:event_weightFocusGained

    private void weightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_weightFocusLost
        // TODO add your handling code here:
        if (weight.getText().equals("")) {
            weight.setText("Weight:");
        }
    }//GEN-LAST:event_weightFocusLost

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateKeyTyped

    private void dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateKeyPressed

    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange

        // TODO add your handling code here:
        
        if (date.getDate() != null) {
            Date dateChoosed = date.getDate(); // Get the selected date
            Calendar selectedDate = Calendar.getInstance();
            selectedDate.setTime(dateChoosed); // Set the selected date into a Calendar object

            // Get the current date
            Calendar currentDate = Calendar.getInstance();

            // Calculate the age
            int ageCalc = currentDate.get(Calendar.YEAR) - selectedDate.get(Calendar.YEAR);

            // Adjust the age if the current date is before the birthday in the current year
            if (currentDate.get(Calendar.MONTH) < selectedDate.get(Calendar.MONTH) ||
                (currentDate.get(Calendar.MONTH) == selectedDate.get(Calendar.MONTH) &&
                 currentDate.get(Calendar.DAY_OF_MONTH) < selectedDate.get(Calendar.DAY_OF_MONTH))) {
                ageCalc--;
            }

            System.out.println(ageCalc); // Print the calculated age
            age.setText(String.valueOf(ageCalc)); // Set the calculated age in the JTextField
        }
        
    }//GEN-LAST:event_datePropertyChange

    private void numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusGained
        if (number.getText().equals("Phone Number:")) {
            number.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_numberFocusGained

    private void numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusLost
        if (number.getText().isEmpty()) {
            number.setText("Phone Number:");
        }
    }//GEN-LAST:event_numberFocusLost

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if (String.valueOf(password.getPassword()).equals("Password:")) {
            password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if (String.valueOf(password.getPassword()).isEmpty()) {
            password.setText("Password:");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passshowMouseClicked

        if (hide) {
            password.setEchoChar('*');
            passshow.setBackground(new Color(204,204,204));
        } else {
            password.setEchoChar((char)0);
            passshow.setBackground(Color.white);
        }
        hide = !hide;
    }//GEN-LAST:event_passshowMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JLabel alreadyhaveanacc;
    private javax.swing.JLabel background;
    private javax.swing.JTextField birthday;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel cm;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JTextField height;
    private javax.swing.JLabel kg;
    private javax.swing.JLabel login;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JLabel passshow;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signup;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
    private int ageCalc;
    private boolean hide = false;
}
